name: Phil Jackson's CV
description: Strong technologist with entrepreneurial tendencies. Two companies founded, Qwerly (CTO), a social media marketing company (acquired by FlipTop) and ApiAxle (CEO/sole founder) which provides an open source API proxy and related tools/services (acquired by Exicon).
markdown: redcarpet
pygments: false
