.PHONY: less

LESS=$(wildcard *.less)
CSS=$(patsubst %.less,%.css,$(LESS))

all: $(CSS)

0.css: 0.less ../cv.less
1.css: 1.less ../cv.less
2.css: 2.less ../cv.less
3.css: 3.less ../cv.less
4.css: 4.less ../cv.less
5.css: 5.less ../cv.less
6.css: 6.less ../cv.less
7.css: 7.less ../cv.less
8.css: 8.less ../cv.less
9.css: 9.less ../cv.less
10.css: 10.less ../cv.less
11.css: 11.less ../cv.less
12.css: 12.less ../cv.less
13.css: 13.less ../cv.less
14.css: 14.less ../cv.less
15.css: 15.less ../cv.less
16.css: 16.less ../cv.less
17.css: 17.less ../cv.less
18.css: 18.less ../cv.less
19.css: 19.less ../cv.less
20.css: 20.less ../cv.less
21.css: 21.less ../cv.less
22.css: 22.less ../cv.less
23.css: 23.less ../cv.less
24.css: 24.less ../cv.less
25.css: 25.less ../cv.less
26.css: 26.less ../cv.less
27.css: 27.less ../cv.less
28.css: 28.less ../cv.less
29.css: 29.less ../cv.less
30.css: 30.less ../cv.less
31.css: 31.less ../cv.less
32.css: 32.less ../cv.less
33.css: 33.less ../cv.less
34.css: 34.less ../cv.less
35.css: 35.less ../cv.less
36.css: 36.less ../cv.less
37.css: 37.less ../cv.less
38.css: 38.less ../cv.less
39.css: 39.less ../cv.less
40.css: 40.less ../cv.less
41.css: 41.less ../cv.less
42.css: 42.less ../cv.less
43.css: 43.less ../cv.less
44.css: 44.less ../cv.less
45.css: 45.less ../cv.less
46.css: 46.less ../cv.less
47.css: 47.less ../cv.less
48.css: 48.less ../cv.less
49.css: 49.less ../cv.less
50.css: 50.less ../cv.less
51.css: 51.less ../cv.less
52.css: 52.less ../cv.less
53.css: 53.less ../cv.less
54.css: 54.less ../cv.less
55.css: 55.less ../cv.less
56.css: 56.less ../cv.less
57.css: 57.less ../cv.less
58.css: 58.less ../cv.less
59.css: 59.less ../cv.less
60.css: 60.less ../cv.less
61.css: 61.less ../cv.less
62.css: 62.less ../cv.less
63.css: 63.less ../cv.less
64.css: 64.less ../cv.less
65.css: 65.less ../cv.less
66.css: 66.less ../cv.less
67.css: 67.less ../cv.less
68.css: 68.less ../cv.less
69.css: 69.less ../cv.less
70.css: 70.less ../cv.less
71.css: 71.less ../cv.less
72.css: 72.less ../cv.less
73.css: 73.less ../cv.less
74.css: 74.less ../cv.less
75.css: 75.less ../cv.less
76.css: 76.less ../cv.less
77.css: 77.less ../cv.less
78.css: 78.less ../cv.less
79.css: 79.less ../cv.less
80.css: 80.less ../cv.less
81.css: 81.less ../cv.less
82.css: 82.less ../cv.less
83.css: 83.less ../cv.less
84.css: 84.less ../cv.less
85.css: 85.less ../cv.less
86.css: 86.less ../cv.less
87.css: 87.less ../cv.less
88.css: 88.less ../cv.less
89.css: 89.less ../cv.less
90.css: 90.less ../cv.less
91.css: 91.less ../cv.less
92.css: 92.less ../cv.less
93.css: 93.less ../cv.less
94.css: 94.less ../cv.less
95.css: 95.less ../cv.less
96.css: 96.less ../cv.less
97.css: 97.less ../cv.less
98.css: 98.less ../cv.less
99.css: 99.less ../cv.less

clean:
	rm -rf $(CSS)

%.css: %.less
	../../node_modules/.bin/lessc $< $@
